language: ruby
rvm:
  - 2.7.6
cache: bundler
before_install:
  - gem install bundler -v '~> 2.1'
  - bundle config build.bcrypt --with-cflags=-Wno-incompatible-pointer-types
  - bundle config build.bindex --with-cflags=-Wno-incompatible-pointer-types
  - bundle config build.websocket-driver --with-cflags=-Wno-incompatible-pointer-types
  - bundle config build.nio4r --with-cflags=-Wno-incompatible-pointer-types
env:
  global:
    - RAILS_ENV=test
services:
  - postgresql
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -U postgres -c 'CREATE DATABASE aquapark_test;' || true
script: bundle exec rspec
bundler_args: ''
