language: ruby
rvm:
  - 3.1.6
cache: bundler
before_install:
  - gem install bundler -v '~> 2.4'
env:
  global:
    - RAILS_ENV=test
services:
  - postgresql
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -U postgres -c 'CREATE DATABASE aquapark_test;' || true
script: bundle exec rspec
bundler_args: ''
